apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: kbessetteudacity/udagram-api-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"