apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    service: udagram-api-feed